use bevy::a11y::{
    accesskit::{NodeBuilder, Role},
    AccessibilityNode,
};
use serde::{Deserialize, Serialize};

use crate::IntoComponent;

#[derive(Clone, Deserialize, Serialize)]
pub struct AccessibilityNodePrefab(RolePrefab);
impl IntoComponent for AccessibilityNodePrefab {
    type Component = AccessibilityNode;
    fn into_component(self) -> Self::Component {
        AccessibilityNode(NodeBuilder::new(self.0.into_role()))
    }
}

#[derive(Clone, Deserialize, Serialize)]
pub enum RolePrefab {
    Unknown,
    InlineTextBox,
    Cell,
    StaticText,
    Image,
    Link,
    Row,
    ListItem,
    ListMarker,
    TreeItem,
    ListBoxOption,
    MenuItem,
    MenuListOption,
    Paragraph,
    GenericContainer,
    CheckBox,
    RadioButton,
    TextInput,
    Button,
    DefaultButton,
    Pane,
    RowHeader,
    ColumnHeader,
    Column,
    RowGroup,
    List,
    Table,
    TableHeaderContainer,
    LayoutTableCell,
    LayoutTableRow,
    LayoutTable,
    Switch,
    ToggleButton,
    Menu,
    MultilineTextInput,
    SearchInput,
    DateInput,
    DateTimeInput,
    WeekInput,
    MonthInput,
    TimeInput,
    EmailInput,
    NumberInput,
    PasswordInput,
    PhoneNumberInput,
    UrlInput,
    Abbr,
    Alert,
    AlertDialog,
    Application,
    Article,
    Audio,
    Banner,
    Blockquote,
    Canvas,
    Caption,
    Caret,
    Code,
    ColorWell,
    ComboBox,
    EditableComboBox,
    Complementary,
    Comment,
    ContentDeletion,
    ContentInsertion,
    ContentInfo,
    Definition,
    DescriptionList,
    DescriptionListDetail,
    DescriptionListTerm,
    Details,
    Dialog,
    Directory,
    DisclosureTriangle,
    Document,
    EmbeddedObject,
    Emphasis,
    Feed,
    FigureCaption,
    Figure,
    Footer,
    FooterAsNonLandmark,
    Form,
    Grid,
    Group,
    Header,
    HeaderAsNonLandmark,
    Heading,
    Iframe,
    IframePresentational,
    ImeCandidate,
    Keyboard,
    Legend,
    LineBreak,
    ListBox,
    Log,
    Main,
    Mark,
    Marquee,
    Math,
    MenuBar,
    MenuItemCheckBox,
    MenuItemRadio,
    MenuListPopup,
    Meter,
    Navigation,
    Note,
    PluginObject,
    Portal,
    Pre,
    ProgressIndicator,
    RadioGroup,
    Region,
    RootWebArea,
    Ruby,
    RubyAnnotation,
    ScrollBar,
    ScrollView,
    Search,
    Section,
    Slider,
    SpinButton,
    Splitter,
    Status,
    Strong,
    Suggestion,
    SvgRoot,
    Tab,
    TabList,
    TabPanel,
    Term,
    Time,
    Timer,
    TitleBar,
    Toolbar,
    Tooltip,
    Tree,
    TreeGrid,
    Video,
    WebView,
    Window,
    PdfActionableHighlight,
    PdfRoot,
    GraphicsDocument,
    GraphicsObject,
    GraphicsSymbol,
    DocAbstract,
    DocAcknowledgements,
    DocAfterword,
    DocAppendix,
    DocBackLink,
    DocBiblioEntry,
    DocBibliography,
    DocBiblioRef,
    DocChapter,
    DocColophon,
    DocConclusion,
    DocCover,
    DocCredit,
    DocCredits,
    DocDedication,
    DocEndnote,
    DocEndnotes,
    DocEpigraph,
    DocEpilogue,
    DocErrata,
    DocExample,
    DocFootnote,
    DocForeword,
    DocGlossary,
    DocGlossRef,
    DocIndex,
    DocIntroduction,
    DocNoteRef,
    DocNotice,
    DocPageBreak,
    DocPageFooter,
    DocPageHeader,
    DocPageList,
    DocPart,
    DocPreface,
    DocPrologue,
    DocPullquote,
    DocQna,
    DocSubtitle,
    DocTip,
    DocToc,
    ListGrid,
    Terminal,
}
impl RolePrefab {
    fn into_role(self) -> Role {
        match self {
            RolePrefab::Abbr => Role::Abbr,
            RolePrefab::Alert => Role::Alert,
            RolePrefab::AlertDialog => Role::AlertDialog,
            RolePrefab::Application => Role::Application,
            RolePrefab::Article => Role::Article,
            RolePrefab::Audio => Role::Audio,
            RolePrefab::Banner => Role::Banner,
            RolePrefab::Blockquote => Role::Blockquote,
            RolePrefab::Button => Role::Button,
            RolePrefab::Canvas => Role::Canvas,
            RolePrefab::Caption => Role::Caption,
            RolePrefab::Caret => Role::Caret,
            RolePrefab::Cell => Role::Cell,
            RolePrefab::CheckBox => Role::CheckBox,
            RolePrefab::Code => Role::Code,
            RolePrefab::ColorWell => Role::ColorWell,
            RolePrefab::Column => Role::Column,
            RolePrefab::ColumnHeader => Role::ColumnHeader,
            RolePrefab::ComboBox => Role::ComboBox,
            RolePrefab::Comment => Role::Comment,
            RolePrefab::Complementary => Role::Complementary,
            RolePrefab::ContentDeletion => Role::ContentDeletion,
            RolePrefab::ContentInfo => Role::ContentInfo,
            RolePrefab::ContentInsertion => Role::ContentInsertion,
            RolePrefab::DateInput => Role::DateInput,
            RolePrefab::DateTimeInput => Role::DateTimeInput,
            RolePrefab::DefaultButton => Role::DefaultButton,
            RolePrefab::Definition => Role::Definition,
            RolePrefab::DescriptionList => Role::DescriptionList,
            RolePrefab::DescriptionListDetail => Role::DescriptionListDetail,
            RolePrefab::DescriptionListTerm => Role::DescriptionListTerm,
            RolePrefab::Details => Role::Details,
            RolePrefab::Dialog => Role::Dialog,
            RolePrefab::Directory => Role::Directory,
            RolePrefab::DisclosureTriangle => Role::DisclosureTriangle,
            RolePrefab::DocAbstract => Role::DocAbstract,
            RolePrefab::DocAcknowledgements => Role::DocAcknowledgements,
            RolePrefab::DocAfterword => Role::DocAfterword,
            RolePrefab::DocAppendix => Role::DocAppendix,
            RolePrefab::DocBackLink => Role::DocBackLink,
            RolePrefab::DocBiblioEntry => Role::DocBiblioEntry,
            RolePrefab::DocBiblioRef => Role::DocBiblioRef,
            RolePrefab::DocBibliography => Role::DocBibliography,
            RolePrefab::DocChapter => Role::DocChapter,
            RolePrefab::DocColophon => Role::DocColophon,
            RolePrefab::DocConclusion => Role::DocConclusion,
            RolePrefab::DocCover => Role::DocCover,
            RolePrefab::DocCredit => Role::DocCredit,
            RolePrefab::DocCredits => Role::DocCredits,
            RolePrefab::DocDedication => Role::DocDedication,
            RolePrefab::DocEndnote => Role::DocEndnote,
            RolePrefab::DocEndnotes => Role::DocEndnotes,
            RolePrefab::DocEpigraph => Role::DocEpigraph,
            RolePrefab::DocEpilogue => Role::DocEpilogue,
            RolePrefab::DocErrata => Role::DocErrata,
            RolePrefab::DocExample => Role::DocExample,
            RolePrefab::DocFootnote => Role::DocFootnote,
            RolePrefab::DocForeword => Role::DocForeword,
            RolePrefab::DocGlossRef => Role::DocGlossRef,
            RolePrefab::DocGlossary => Role::DocGlossary,
            RolePrefab::DocIndex => Role::DocIndex,
            RolePrefab::DocIntroduction => Role::DocIntroduction,
            RolePrefab::DocNoteRef => Role::DocNoteRef,
            RolePrefab::DocNotice => Role::DocNotice,
            RolePrefab::DocPageBreak => Role::DocPageBreak,
            RolePrefab::DocPageFooter => Role::DocPageFooter,
            RolePrefab::DocPageHeader => Role::DocPageHeader,
            RolePrefab::DocPageList => Role::DocPageList,
            RolePrefab::DocPart => Role::DocPart,
            RolePrefab::DocPreface => Role::DocPreface,
            RolePrefab::DocPrologue => Role::DocPrologue,
            RolePrefab::DocPullquote => Role::DocPullquote,
            RolePrefab::DocQna => Role::DocQna,
            RolePrefab::DocSubtitle => Role::DocSubtitle,
            RolePrefab::DocTip => Role::DocTip,
            RolePrefab::DocToc => Role::DocToc,
            RolePrefab::Document => Role::Document,
            RolePrefab::EditableComboBox => Role::EditableComboBox,
            RolePrefab::EmailInput => Role::EmailInput,
            RolePrefab::EmbeddedObject => Role::EmbeddedObject,
            RolePrefab::Emphasis => Role::Emphasis,
            RolePrefab::Feed => Role::Feed,
            RolePrefab::Figure => Role::Figure,
            RolePrefab::FigureCaption => Role::FigureCaption,
            RolePrefab::FooterAsNonLandmark => Role::FooterAsNonLandmark,
            RolePrefab::Footer => Role::Footer,
            RolePrefab::Form => Role::Form,
            RolePrefab::GenericContainer => Role::GenericContainer,
            RolePrefab::GraphicsDocument => Role::GraphicsDocument,
            RolePrefab::GraphicsObject => Role::GraphicsObject,
            RolePrefab::GraphicsSymbol => Role::GraphicsSymbol,
            RolePrefab::Grid => Role::Grid,
            RolePrefab::Group => Role::Group,
            RolePrefab::HeaderAsNonLandmark => Role::HeaderAsNonLandmark,
            RolePrefab::Header => Role::Header,
            RolePrefab::Heading => Role::Heading,
            RolePrefab::Iframe => Role::Iframe,
            RolePrefab::IframePresentational => Role::IframePresentational,
            RolePrefab::Image => Role::Image,
            RolePrefab::ImeCandidate => Role::ImeCandidate,
            RolePrefab::InlineTextBox => Role::InlineTextBox,
            RolePrefab::Keyboard => Role::Keyboard,
            RolePrefab::LayoutTable => Role::LayoutTable,
            RolePrefab::LayoutTableCell => Role::LayoutTableCell,
            RolePrefab::LayoutTableRow => Role::LayoutTableRow,
            RolePrefab::Legend => Role::Legend,
            RolePrefab::LineBreak => Role::LineBreak,
            RolePrefab::Link => Role::Link,
            RolePrefab::ListBox => Role::ListBox,
            RolePrefab::List => Role::List,
            RolePrefab::ListBoxOption => Role::ListBoxOption,
            RolePrefab::ListGrid => Role::ListGrid,
            RolePrefab::ListItem => Role::ListItem,
            RolePrefab::ListMarker => Role::ListMarker,
            RolePrefab::Log => Role::Log,
            RolePrefab::Main => Role::Main,
            RolePrefab::Mark => Role::Mark,
            RolePrefab::Marquee => Role::Marquee,
            RolePrefab::Math => Role::Math,
            RolePrefab::Menu => Role::Menu,
            RolePrefab::MenuBar => Role::MenuBar,
            RolePrefab::MenuItem => Role::MenuItem,
            RolePrefab::MenuItemCheckBox => Role::MenuItemCheckBox,
            RolePrefab::MenuItemRadio => Role::MenuItemRadio,
            RolePrefab::MenuListOption => Role::MenuListOption,
            RolePrefab::MenuListPopup => Role::MenuListPopup,
            RolePrefab::Meter => Role::Meter,
            RolePrefab::MonthInput => Role::MonthInput,
            RolePrefab::MultilineTextInput => Role::MultilineTextInput,
            RolePrefab::Navigation => Role::Navigation,
            RolePrefab::Note => Role::Note,
            RolePrefab::NumberInput => Role::NumberInput,
            RolePrefab::Pane => Role::Pane,
            RolePrefab::Paragraph => Role::Paragraph,
            RolePrefab::PasswordInput => Role::PasswordInput,
            RolePrefab::PdfActionableHighlight => Role::PdfActionableHighlight,
            RolePrefab::PdfRoot => Role::PdfRoot,
            RolePrefab::PhoneNumberInput => Role::PhoneNumberInput,
            RolePrefab::PluginObject => Role::PluginObject,
            RolePrefab::Portal => Role::Portal,
            RolePrefab::Pre => Role::Pre,
            RolePrefab::ProgressIndicator => Role::ProgressIndicator,
            RolePrefab::RadioButton => Role::RadioButton,
            RolePrefab::RadioGroup => Role::RadioGroup,
            RolePrefab::Region => Role::Region,
            RolePrefab::RootWebArea => Role::RootWebArea,
            RolePrefab::RowGroup => Role::RowGroup,
            RolePrefab::Row => Role::Row,
            RolePrefab::RowHeader => Role::RowHeader,
            RolePrefab::Ruby => Role::Ruby,
            RolePrefab::RubyAnnotation => Role::RubyAnnotation,
            RolePrefab::ScrollBar => Role::ScrollBar,
            RolePrefab::ScrollView => Role::ScrollView,
            RolePrefab::Search => Role::Search,
            RolePrefab::SearchInput => Role::SearchInput,
            RolePrefab::Section => Role::Section,
            RolePrefab::Slider => Role::Slider,
            RolePrefab::SpinButton => Role::SpinButton,
            RolePrefab::Splitter => Role::Splitter,
            RolePrefab::StaticText => Role::StaticText,
            RolePrefab::Status => Role::Status,
            RolePrefab::Strong => Role::Strong,
            RolePrefab::Suggestion => Role::Suggestion,
            RolePrefab::SvgRoot => Role::SvgRoot,
            RolePrefab::Switch => Role::Switch,
            RolePrefab::TabList => Role::TabList,
            RolePrefab::TabPanel => Role::TabPanel,
            RolePrefab::TableHeaderContainer => Role::TableHeaderContainer,
            RolePrefab::Table => Role::Table,
            RolePrefab::Tab => Role::Tab,
            RolePrefab::Terminal => Role::Terminal,
            RolePrefab::Term => Role::Term,
            RolePrefab::TextInput => Role::TextInput,
            RolePrefab::TimeInput => Role::TimeInput,
            RolePrefab::Timer => Role::Timer,
            RolePrefab::Time => Role::Time,
            RolePrefab::TitleBar => Role::TitleBar,
            RolePrefab::ToggleButton => Role::ToggleButton,
            RolePrefab::Toolbar => Role::Toolbar,
            RolePrefab::Tooltip => Role::Tooltip,
            RolePrefab::Tree => Role::Tree,
            RolePrefab::TreeGrid => Role::TreeGrid,
            RolePrefab::TreeItem => Role::TreeItem,
            RolePrefab::Unknown => Role::Unknown,
            RolePrefab::UrlInput => Role::UrlInput,
            RolePrefab::Video => Role::Video,
            RolePrefab::WebView => Role::WebView,
            RolePrefab::WeekInput => Role::WeekInput,
            RolePrefab::Window => Role::Window,
        }
    }
}
